-- Criação do banco de dados e usuário para o webui
CREATE DATABASE webui;

CREATE USER webui WITH PASSWORD 'webui_password' SUPERUSER;

GRANT ALL PRIVILEGES ON DATABASE webui TO webui;
GRANT CONNECT ON DATABASE webui TO webui;
GRANT USAGE ON SCHEMA public TO webui;
GRANT CREATE ON SCHEMA public TO webui;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO webui;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO webui;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO webui;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO webui;

-- Criação do banco de dados e usuário para o langflow
CREATE DATABASE langflow;

CREATE USER langflow WITH PASSWORD 'langflow_password' SUPERUSER;

GRANT ALL PRIVILEGES ON DATABASE langflow TO langflow;
GRANT CONNECT ON DATABASE langflow TO langflow;
GRANT USAGE ON SCHEMA public TO langflow;
GRANT CREATE ON SCHEMA public TO langflow;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO langflow;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO langflow;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO langflow;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO langflow;
